//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageCropping_Ananta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Image
    {
        public int Id { get; set; }
        public string ImageName { get; set; }
        public byte[] Image { get; set; }
        public string coordinateX { get; set; }
        public string CordinateY { get; set; }
        public string Height { get; set; }
        public string Width { get; set; }
        public string leftCropped { get; set; }
        public string topCropped { get; set; }
    }
}
